#ifndef ERTBOT_CONFIG_H
#define ERTBOT_CONFIG_H
//Github
//#define GITHUB_API_TOKEN getenv("GITHUB_API_TOKEN")
#define USER_AGENT "My-CURL-Program-ZUGMA" //User-Agent header required by GitHub API
#define REPO_URL "https://api.github.com/repos/EPFLRocketTeam/ert_wiki/contents" //GitHub repository URL and image path


//Wiki
//#define WIKI_API_TOKEN getenv("WIKI_API_TOKEN")
#define LINK_TRACKER_PAGE_ID "896"
#define IMAGE_TRACKER_PAGE_ID "898"
#define SYNC_TRACKER_PAGE_ID "899"
#define PAGE_SUBSCRIPTION_TRACKER_PAGE_ID "900"
#define ACCRONYM_TRACKER_PAGE_ID "901"
#define BROKEN_LINKS_TRACKER_PAGE_ID "870"
#define TEST_DRL_PAGE_ID "1125"
#define TEST_REQ_PAGE_ID "1132"

//Slack
//Define your Slack API token and the channel where you want to upload the file
//#define SLACK_API_TOKEN getenv("SLACK_API_TOKEN")
#define SLACK_WIKI_TOOLBOX_CHANNEL "C06RQGVRKPU"

//Sheet
//#define SHEET_API_TOKEN getenv("SHEET_API_TOKEN")



//Local
#define ACCRONYM_LIST_PATH "./accronymList"
#define LOCAL_FILE_PATH "Users/Ryan/Desktop/Code/Wiki_Toolbox/ERTWikiToolbox-Structure-Change/test/include"

//Requirements
#define REQ_ID_COL 0
#define REQ_TITLE_COL 1
#define REQ_DESCRIPTION_COL 2
#define REQ_SOURCE_COL 3
#define REQ_AUTHOR_COL 4
#define REQ_JUSTIFICATION_COL 5
#define REQ_CRITICALITY_COL 6
#define REQ_COMPLIANCE_COL 7
#define REQ_VERIFICATION_STATUS_COL 8
#define REQ_ASSIGNEE_COL 9
#define REQ_REVIEW_1_VERIFICATION_1_METHOD_COL 10
#define REQ_REVIEW_1_VERIFICATION_1_STATUS_COL 11
#define REQ_REVIEW_1_VERIFICATION_2_METHOD_COL 12
#define REQ_REVIEW_1_VERIFICATION_2_STATUS_COL 13
#define REQ_REVIEW_1_VERIFICATION_3_METHOD_COL 14
#define REQ_REVIEW_1_VERIFICATION_3_STATUS_COL 15
#define REQ_REVIEW_2_VERIFICATION_1_METHOD_COL 16
#define REQ_REVIEW_2_VERIFICATION_1_STATUS_COL 17
#define REQ_REVIEW_2_VERIFICATION_2_METHOD_COL 18
#define REQ_REVIEW_2_VERIFICATION_2_STATUS_COL 19
#define REQ_REVIEW_2_VERIFICATION_3_METHOD_COL 20
#define REQ_REVIEW_2_VERIFICATION_3_STATUS_COL 21
#define REQ_REVIEW_3_VERIFICATION_1_METHOD_COL 22
#define REQ_REVIEW_3_VERIFICATION_1_STATUS_COL 23
#define REQ_REVIEW_3_VERIFICATION_2_METHOD_COL 24
#define REQ_REVIEW_3_VERIFICATION_2_STATUS_COL 25
#define REQ_REVIEW_3_VERIFICATION_3_METHOD_COL 26
#define REQ_REVIEW_3_VERIFICATION_3_STATUS_COL 27
#define REQ_REVIEW_4_VERIFICATION_1_METHOD_COL 28
#define REQ_REVIEW_4_VERIFICATION_1_STATUS_COL 29
#define REQ_REVIEW_4_VERIFICATION_2_METHOD_COL 30
#define REQ_REVIEW_4_VERIFICATION_2_STATUS_COL 31
#define REQ_REVIEW_4_VERIFICATION_3_METHOD_COL 32
#define REQ_REVIEW_4_VERIFICATION_3_STATUS_COL 33
#define REQ_REVIEW_5_VERIFICATION_1_METHOD_COL 34
#define REQ_REVIEW_5_VERIFICATION_1_STATUS_COL 35
#define REQ_REVIEW_5_VERIFICATION_2_METHOD_COL 36
#define REQ_REVIEW_5_VERIFICATION_2_STATUS_COL 37
#define REQ_REVIEW_5_VERIFICATION_3_METHOD_COL 38
#define REQ_REVIEW_5_VERIFICATION_3_STATUS_COL 39
#define REQ_REVIEW_6_VERIFICATION_1_METHOD_COL 40
#define REQ_REVIEW_6_VERIFICATION_1_STATUS_COL 41
#define REQ_REVIEW_6_VERIFICATION_2_METHOD_COL 42
#define REQ_REVIEW_6_VERIFICATION_2_STATUS_COL 43
#define REQ_REVIEW_6_VERIFICATION_3_METHOD_COL 44
#define REQ_REVIEW_6_VERIFICATION_3_STATUS_COL 45




#define REQ_SHEET_EMPTY_VALUE "N/A"
#define MAXIMUM_NUMBER_OF_VERIFICATIONS_PER_REVIEW 3
#define MAXIMUM_NUMBER_OF_REVIEWS 6


#define REVIEW_1_NAME "TRR"
#define REVIEW_2_NAME "CDR"
#define REVIEW_3_NAME "SIR"
#define REVIEW_4_NAME "SAR"
#define REVIEW_5_NAME "ORR"
#define REVIEW_6_NAME "FRR"


#define CURRENT_REVIEW 1
#endif
