name: Run Unit Tests

on:
  push:
    branches:
      - main
      - dev # Include feature branches if necessary
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure Script is Available
        run: cp ~/ERTbot_source_files/ERTbot/build_and_run.sh /home/runner/work/ERTbot/scripts/build_and_run.sh

      - name: Run Custom Build Script
        run: ./scripts/build_and_test.sh --rebuild --run-tests

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          files: |
            test-results.xml
