name: Run Unit Tests

on:
  push:
    branches:
      - main
      - dev # Include feature branches if necessary
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure directory exists and copy script
        run: |
          mkdir -p ./scripts  # Ensure relative path exists
          cp ~/ERTbot_source_files/ERTbot/build_and_run.sh ./scripts/build_and_run.sh

      - name: Run Custom Build Script
        run: ./scripts/build_and_run.sh --rebuild --run-tests

      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: |
            test-results.tap
